@BaseUrl  = http://localhost:3001
###
POST  {{BaseUrl}}/api/users/login
Content-Type: application/json

{
    "userName": "hasan",
    "password": "123456"
}
###
GET {{BaseUrl}}/api/recipes
###
POST  {{BaseUrl}}/api/users/
Content-Type: application/json

{
    "userName": "zehraa",
    "email":"asddd@gmail.com",
    "password": "123456"
}
###

GET {{BaseUrl}}/api/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Imhhc2FuIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE3MjM2NjUwNTMsImV4cCI6MTcyMzc1MTQ1M30.v_MC7Xgqd3Aci-OaaTcELpfNEs62inMewhWmyYXxilA

###
GET {{BaseUrl}}/api/recipes/users/hasan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Imhhc2FuIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE3MjM2NjUwNTMsImV4cCI6MTcyMzc1MTQ1M30.v_MC7Xgqd3Aci-OaaTcELpfNEs62inMewhWmyYXxilA